### PR TITLE
Demo fix

### PR DESCRIPTION
**Pull request by Nayte91**
Small fix to make the demo works, as I had trouble to launch it.

Please try without this fix:
1. clone a fresh new version of the repository,
2. do a npm install
3. do a npm build:demo
4. do a npm start (or run start, what is the difference?)
5. try to access to localhost:3001
6. notice that it doesn't work.

With my fix, you can go back through this process, and it will work.

My setup:
node v16.17.0
npm v8.15.0

### CODE REVIEW

**Comment by dc7290** [comment]
@Nayte91 

Thank you!

Sorry, the README is not sufficiently clear.
Currently, the root URL of the development server started by `npm start` is `http://localhost:3001/react-hooks-use-modal`.
(You can omit the run for certain commands when doing an npm run https://docs.npmjs.com/cli/v7/commands/npm-run-script#description)

May I ask for an addendum to the README?

**Comment by Nayte91** [comment]
Thank you for the tip on npm run!

I understand now. Few questions:

- Do you use build:demo? What is your use case?
- [L221](https://github.com/microcmsio/react-hooks-use-modal/blob/610974ad9c47049039421519b252f66beedb7181/README.md?plain=1#L221) you point out `http://localhost:3001` only, is there a use case where you access only to this url?

Otherwise I'ld fix the readme as my PR suggests :)

**Comment by dc7290** [comment]
@Nayte91 
Sorry for the late reply.

As for `build:demo`, this is the build command before deploying the demo site!
I don't think it will be used very often, so I thought you could remove the `Build demo` from the README!
May I ask you to do this too?

> [L221](https://github.com/microcmsio/react-hooks-use-modal/blob/610974ad9c47049039421519b252f66beedb7181/README.md?plain=1#L221) you point out http://localhost:3001 only, is there a use case where you access only to this url?

This is necessary because we are running examples during development to make sure it works!

**Comment by Nayte91** [comment]
Hello @dc7290,

That's ok, I removed the build:demo step and ensured everything else still works fine.

**Comment by dc7290** [comment]
Thanks!!

**Pull request merged**
